#!/bin/sh
# File generated by ocamlbuild

cd /home/user/Projects/MicroFluidics/basic_trial

rm -f basic_types.cmi
# Also clean the script itself
rm -f /home/user/Projects/MicroFluidics/basic_trial/_build/sanitize.sh
